<a href="https://colab.research.google.com/github/minnji88/NLP-study/blob/main/1_Pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python List

In [ ]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [ ]:
print(list1[0], list1[-1]) #인덱스가 음수일 경우 리스트의 끝에서부터 셈

1 3


In [ ]:
list2 = range(10)
print(list2)
print(type(list2))

range(0, 10)
<class 'range'>


In [ ]:
print(list2[2:4]) # 인덱스 2에서 4(제외)까지 슬라이싱
print(list2[2:]) # 인덱스 2에서 끝까지 슬라이싱
print(list2[:2]) # 처음부터 인덱스 2(제외)까지 슬라이싱
print(list2[:]) # 전체 리스트 슬라이싱
print(list2[::2]) # 2씩 증가하면서 리스트 출력
print(list2[:-1]) # 슬라이싱 인덱스는 음수도 가능

range(2, 4)
range(2, 10)
range(0, 2)
range(0, 10)
range(0, 10, 2)
range(0, 9)


## For Loop

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
  print(animal)

cat
dog
monkey


In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
  squares.append(x ** 2)

print(squares)

[0, 1, 4, 9, 16]


## Function(1)

In [ ]:
def sign(x):
  if x > 0:
    return "positive"
  elif x < 0:
    return "negative"
  else:
    return "zero"

for x in [-1, 0, 1]:
  print(sign(x))

negative
zero
positive


## Function(2)

In [ ]:
def hello(name, loud = False):
  if loud:
    print('Hello, %s!' % name.upper())
  else:
    print('Hello, %s' % name)

hello('Bob')
hello('Fred', loud = True)

Hello, Bob
Hello, FRED!


## Python zip

In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
  print(x, y, z)

1 4 7
2 5 8
3 6 9


##  __call__

In [ ]:
class HelloWorld():
  def __init__(self): # 생성자
    pass
  def __call__(self):
    print("Hello world")

helloworld = HelloWorld() 
helloworld() # Hello world 콜함수 실행

Hello world


## Numpy

In [ ]:
import numpy as np

a = np.array([1, 2, 3]) # rank가 1인 배열 생성
print(type(a))
print(a.shape)
print(a.ndim)           # 출력 "1"
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b.ndim)
print(b[0,0], b[0,1], b[0,2])

<class 'numpy.ndarray'>
(3,)
1
1 2 3
[5 2 3]
(2, 3)
2
1 2 3


In [ ]:
import numpy as np

a = np.zeros((2, 2)) # 모든 값이 0인 배열 생성
print(a)

b = np.ones((1, 2)) # 모든 값이 1인 배열 생성
print(b)

c = np.full((2,2), 7) # 모든 값이 특정 상수인 배열 생성
print(c)

d = np.eye(2) # 2x2 단위행렬 생성
print(d)

e = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print(e)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.64106548 0.68956458]
 [0.54558926 0.13961947]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

# 슬라이싱을 이용하여 첫 두 행과 1열, 2열로 이루어진 부분배열 생성;
# b는 shape가 (2,2)인 배열이 됨: # [[2 3]
# [67]]
b = a[:2, 1:3]
print(b)

# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조, 즉 슬라이싱된 배열을 수정하면
# 원본 배열 역시 수정됨.
print(a[0, 1])

b[0, 0] = 77 
print(b)

print(a[0, 1])
# 출력 "2"
# b[0, 0]은 a[0, 1]과 같은 데이터
# 출력 "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
[[77  3]
 [ 6  7]]
77


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

a = np.reshape(a, (2,6)) 
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
print(np.arange(10, 50)) #[10, 50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
print(np.arange(10, 50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))  # np.where(조건) 조건만 쓰면 조건에 맞는 데이터의 인덱스를 반환

(array([1, 3, 5, 7]),)


In [ ]:
a = np.arange(9).reshape(3, 3)
print(a)
print(a+1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = np.arange(9).reshape(3, 3)
print(a[[1, 0, 2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [ ]:
a = np.array((3, -2, 2, -1, 3))
print(a[np.where(a>=0)])

[3 2 3]


## Tensor

In [ ]:
import torch
import numpy as np

t1 = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(t1)

t2 = torch.tensor(np.arange(7))
print(t2)

print(t1.shape, t2.shape)

print(t1.dim())
print(t1.shape)
print(t1.size())
print(t1[:2], t1[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([0, 1, 2, 3, 4, 5, 6])
torch.Size([7]) torch.Size([7])
1
torch.Size([7])
torch.Size([7])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## Broadcasting

차원이 달라도 연산이 되는

In [ ]:
import torch 
import numpy as np

m1 = torch.FloatTensor([[3, 3]]) 
m2 = torch.FloatTensor([[2, 2]]) 
print(m1 + m2)

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]] #m2 = torch.FloatTensor(3) # 3 -> Error \
print(m1 + m2)

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) 
m2 = torch.FloatTensor([[3], [4]]) 
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


## Mul vs MatMul

In [ ]:
print('-------------')
print('Mul vs Matmul') 
print('-------------')

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]]) 
print('Shape of Matrix 1: ', m1.shape) # 2 x 2 
print('Shape of Matrix 2: ', m2.shape) # 2 x 1 
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

t.mean(dim=0): 첫번째 차원단위 평균

In [ ]:
import torch
import numpy as np

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.type())
print(t)

print(t.mean())
# 행방향 평균
print(t.mean(dim = 0))
# 열방향 평균
print(t.mean(dim = 1))
# dim=-1일 경우, 그 행렬의 마지막 차원을 얘기하는 것
print(t.mean(dim = -1)) # 여기선 2차원

torch.FloatTensor
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## View (Numpy: Reshape) 원소의 수를 유지하면서 텐서의 크기 변경

- 파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 함
- Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할

In [ ]:
import torch 
import numpy as np

# 3차원 텐서의 크기 변경
# '-1'이 들어가 있는 '행(row)' 의 개수가 가변적으로 정해짐을 알 수 있습니다

t = np.arange(12).reshape(-1, 2, 3) 
print(t)
print(t.shape)

floatT = torch.FloatTensor(t) 
print(floatT.shape)
print(floatT.view([-1, 3]))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


## Practice

In [ ]:
import torch 
import numpy as np
t = np.arange(24) 
print(t.shape)
floatT = torch.FloatTensor(t) 
print(floatT.view([-1, 2, 3]))

(24,)
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [15., 16., 17.]],

        [[18., 19., 20.],
         [21., 22., 23.]]])


## Linear Regression

### Theoretical Overview

$$ H(x) = Wx + b $$
$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2 $$

$H(x)$: 주어진 $x$ 값에 대해 예측을 어떻게 할 것인가

$cost(W, b)$: $H(x)$ 가 $y$ 를 얼마나 잘 예측했는가

## Imports

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## Data

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


## Weight Initialization

`requires_grad` 속성을 `True` 로 설정하면, 

그 tensor에서 이뤄진 모든 연산들을 추적(track)하기 시작합니다

In [ ]:
# 모델 초기화
W = torch.zeros(1, requires_grad= True)
print(W)

b = torch.zeros(1, requires_grad= True)
print(b)


tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


## Hypothesis

$$ H(x) = Wx + b $$

In [ ]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


## Cost

$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2 $$

In [ ]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [ ]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [ ]:
print(hypothesis - y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [ ]:
print((hypothesis - y_train) ** 2)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)


In [ ]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


## Gradient Descent

Pytorch의 `SGD`나 `Adam`과 같은 optimizer 해결

`Optimzer`는 `update할 parameter`와 `learning rate` 및 여러 다른 hyper-parameter를 받아 `step()` method 를 통해 업데이트한다.

Gradient를 0으로 만드는 것도 optimizer의 zero_grad() method 가 해결해 준다.


In [ ]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr = 0.01)

모든 gradient를 구하려면 backward() method를 사용한다

In [ ]:
optimizer.zero_grad()
# cost.backward 비용 함수로부터 기울기를 구하라는 의미
cost.backward()
optimizer.step()

In [ ]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [ ]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [ ]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


## Full Code

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train * W + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1000 W: 0.093, b: 0.040 Cost: 4.666667
Epoch  100/1000 W: 0.873, b: 0.289 Cost: 0.012043
Epoch  200/1000 W: 0.900, b: 0.227 Cost: 0.007442
Epoch  300/1000 W: 0.921, b: 0.179 Cost: 0.004598
Epoch  400/1000 W: 0.938, b: 0.140 Cost: 0.002842
Epoch  500/1000 W: 0.951, b: 0.110 Cost: 0.001756
Epoch  600/1000 W: 0.962, b: 0.087 Cost: 0.001085
Epoch  700/1000 W: 0.970, b: 0.068 Cost: 0.000670
Epoch  800/1000 W: 0.976, b: 0.054 Cost: 0.000414
Epoch  900/1000 W: 0.981, b: 0.042 Cost: 0.000256
Epoch 1000/1000 W: 0.985, b: 0.033 Cost: 0.000158



점점 $H(x)$ 의 $W$ 와 $b$ 를 조정해서 cost가 줄어드는 것을 볼 수 있습니다.

## High-level Implementation with nn.Module

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

이제 linear regression 모델을 만들면 되는데, 기본적으로 PyTorch의 모든 모델은 제공되는 nn.Module을 inherit 해서 만들게 됩니다.

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)


모델의 __init__에서는 사용할 레이어들을 정의하게 됩니다. 여기서 우리는 linear regression 모델을 만들기 때문에, nn.Linear 를 이용할 것입니다. 그리고 forward에서는 이 모델이 어떻게 입력값에서 출력값을 계산하는지 알려줍니다.

In [ ]:
model = LinearRegressionModel()

## Hypothesis

이제 모델을 생성해서 예측값 $H(x)$를 구해보자

In [ ]:
hypothesis = model(x_train)

In [ ]:
print(hypothesis)

tensor([[1.5073],
        [2.1321],
        [2.7569]], grad_fn=<AddmmBackward>)


## Cost

이제 mean squared error (MSE) 로 cost를 구해보자. MSE 역시 PyTorch에서 기본적으로 제공한다.

In [ ]:
cost = F.mse_loss(hypothesis, y_train)
print(cost)

tensor(0.1113, grad_fn=<MseLossBackward>)


## Gradient Descent

마지막 주어진 cost를 이용해 $H(x)$ 의 $W, b$ 를 바꾸어서 cost를 줄여봅니다. 이때 PyTorch의 torch.optim 에 있는 optimizer 들 중 하나를 사용할 수 있습니다.

In [ ]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [ ]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
model = LinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, cost.item()
        ))

Epoch    0/1000 W: -0.576, b: -0.856 Cost: 22.404322
Epoch  100/1000 W: 1.047, b: -0.107 Cost: 0.001657
Epoch  200/1000 W: 1.037, b: -0.084 Cost: 0.001024
Epoch  300/1000 W: 1.029, b: -0.066 Cost: 0.000633
Epoch  400/1000 W: 1.023, b: -0.052 Cost: 0.000391
Epoch  500/1000 W: 1.018, b: -0.041 Cost: 0.000242
Epoch  600/1000 W: 1.014, b: -0.032 Cost: 0.000149
Epoch  700/1000 W: 1.011, b: -0.025 Cost: 0.000092
Epoch  800/1000 W: 1.009, b: -0.020 Cost: 0.000057
Epoch  900/1000 W: 1.007, b: -0.016 Cost: 0.000035
Epoch 1000/1000 W: 1.005, b: -0.012 Cost: 0.000022
