<a href="https://colab.research.google.com/github/minnji88/NLP-study/blob/main/3_2_Torch_nn_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import torch.nn as nn

In [11]:
train_data = 'you need to know how to code'
word_set = set(train_data.split()) # 중복을 제거한 단어들의 집합인 단어 집합 생성.
vocab = {word: i+2 for i, word in enumerate(word_set)}  # 단어 집합의 각 단어에 고유한 정수 맵핑.
vocab['<unk>'] = 0 # unknown 토큰
vocab['<pad>'] = 1 # 문자열의 길이를 맞춰주는 padding 토큰 
print(vocab)

{'to': 2, 'you': 3, 'know': 4, 'code': 5, 'how': 6, 'need': 7, '<unk>': 0, '<pad>': 1}


In [12]:
# 단어 집합의 크기만큼의 행을 가지는 임베딩 테이블 생성.
embedding_table = torch.FloatTensor([
                               [ 0.0,  0.0,  0.0],
                               [ 0.0,  0.0,  0.0],
                               [ 0.2,  0.9,  0.3],
                               [ 0.1,  0.5,  0.7],
                               [ 0.2,  0.1,  0.8],
                               [ 0.4,  0.1,  0.1],
                               [ 0.1,  0.8,  0.9],
                               [ 0.6,  0.1,  0.1]])

In [13]:
# 임의의 샘플 문장
sample = 'you need to run'.split()
idxes=[]
# 각 단어를 정수로 변환
for word in sample:
  try:
    idxes.append(vocab[word])
  except KeyError: # 단어 집합에 없는 단어일 경우 <unk>로 대체된다.
    idxes.append(vocab['<unk>'])
idxes = torch.LongTensor(idxes)
print(idxes)

# 룩업 테이블
lookup_result = embedding_table[idxes, :] # 각 정수를 인덱스로 임베딩 테이블에서 값을 가져온다.
print(lookup_result)

tensor([3, 7, 2, 0])
tensor([[0.1000, 0.5000, 0.7000],
        [0.6000, 0.1000, 0.1000],
        [0.2000, 0.9000, 0.3000],
        [0.0000, 0.0000, 0.0000]])


In [14]:
train_data = 'you need to know how to code'
word_set = set(train_data.split()) # 중복을 제거한 단어들의 집합인 단어 집합 생성.
vocab = {tkn: i+2 for i, tkn in enumerate(word_set)}  # 단어 집합의 각 단어에 고유한 정수 맵핑.
vocab['<unk>'] = 0
vocab['<pad>'] = 1

In [15]:
embedding_layer = nn.Embedding(num_embeddings = len(vocab), 
                               embedding_dim = 3,
                               padding_idx = 1)

In [16]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 1.5445, -2.0409,  1.2758],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.8820,  0.4425,  1.7675],
        [-0.6918,  0.1902,  0.7226],
        [-1.7587, -0.0400,  0.2853],
        [ 0.6229, -0.7249, -0.3257],
        [-0.4559,  0.1322, -0.2601],
        [ 1.4274, -0.0087,  1.1540]], requires_grad=True)
